### ISSUE TITLE
Show Cargo errors

### ISSUE THREAD

**Issue by torkleyy** [AtomLinter/linter-rust#98]
Consider this example:

```toml
[package]
name = "foo"
version = "0.1.0"
authors = ["me <me@my-email.com>"]

[dependencies]
libx = "*"
```

It would be nice if the linter showed you that `libx` does not exist.
